*******************************************************************************
****** lab1inv_basic schematic ece4740  <vs>  lab1inv_basic layout ece4740
*******************************************************************************

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(nmos1v) MOS                                      1       1           1       1
(pmos1v) MOS                                      1       1           1       1

Match Statistics
================                                  Total             Unmatched
Cell/Device                               schematic  layout   schematic  layout
(nmos1v) MOS                                      1       1           0       0
(pmos1v) MOS                                      1       1           0       0
                                             ------  ------      ------  ------
Total                                             2       2           0       0

Match Statistics for Nets                         4       4           0       0

================================================================[lab1inv_basic]
====== Unbound Pin ============================================================
===============================================================================

S Y

================================================================[lab1inv_basic]
====== Summary of Errors ======================================================
===============================================================================

Schematic  Layout     Error Type
---------  ------     ----------
 1          -         Unbound Pin

